version: '3.8'

services:
  web:
    image: php:8.2-apache
    volumes:
      - .:/var/www/html
    environment:
      DATABASE_URL: mysql://myxgwrd6h4msa70v:agfvorpz68z6gmy5@klbcedmmqp7w17ik.cbetxkdyhwsb.us-east-1.rds.amazonaws.com:3306/tvk9yju0k1g59m0n
    ports:
      - ${PORT:80}
